version: "3.8"

services:
  app:
    build: . 
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app #mount the current directory to the container
    env_file:
      - .env.docker
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
