"""Add captains_ids to clubs table

Revision ID: 254aaf285d7c
Revises: eabd1638a9ba
Create Date: 2025-05-27 18:58:00.159942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '254aaf285d7c'
down_revision: Union[str, None] = 'eabd1638a9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('captains_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('clubs', 'captains')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('captains', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('clubs', 'captains_ids')
    # ### end Alembic commands ###
